### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by RaviKumarK25** [ibmkynl/ChitChat#1]
Hi, i am getting error while running you code. Please help me to solve this issue. 

Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.
* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 882

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 8s
Exception: Gradle task assembleDebug failed with exit code 1

Note: I am using latest version of flutter and co.

**Comment by ibmkynl** [comment]
Do you get any error on code or warning? I can still run the code without
error. You can try to create a new project and copy paste the code. That
should work. Also don't forget to implement your own firebase connection.

RaviKumarK25 <notifications@github.com>, 14 Tem 2020 Sal, 18:18 tarihinde
şunu yazdı:

**Comment by RaviKumarK25** [comment]
Hi yes, exactly i have done what you said. Now its working without any error! Thanks for your reply

**Comment by Devanshu-Suri** [comment]
Hello, when I am running your code in an emulator, in the search tab bar section after all the profiles finished displaying when I click on the cross button, then the screen becomes red and on the emulator, it says "Invalid argument(s)". Can u please help me out to remove this(I think that happens when it fails to find more users).
Actually, I also tried by adding some else condition in your search page when the event is LoadUser event but it didn't work.

**Comment by ibmkynl** [comment]
Hello,
Probably that error happened because i didn't check if there is a user to
match or not (if you match with all users) you should check that. What did
you want to add on the loadUser event ? Did you check the Search bloc for
this? First you need to change Search bloc correctly and then you can make
changes on UI. If you can be more specific I could help.


Devanshu-Suri <notifications@github.com>, 24 Tem 2020 Cum, 20:12 tarihinde
şunu yazdı:

**Comment by Devanshu-Suri** [comment]
I just want that if there is no user to show then it will return an image, can u plz help me in this. YES I have seen the search bloc and tried to make a new event for that but it didn't worked for me , 
 after that I place this condition 
if (_user!=null)
{ your code when event is Loaduser event} 
else if(_user=null{return image return code}

 but eventually it did'nt worked out .

**Comment by ibmkynl** [comment]
What is the error ? First check the repo , you will see getUser() this gets
the next user to show. Check if that function returns a user or null.
Because the app first calls getUser() before your code calling. error can
happen before your code works. Also don't forget the getDifference()
function. You should add that function into your if else statement. if the
user returns null or something that function will give error too.

Devanshu-Suri <notifications@github.com>, 24 Tem 2020 Cum, 21:54 tarihinde
şunu yazdı:

**Comment by Devanshu-Suri** [comment]
It's working now thank you sir.
